// declare var App
// declare var dungeonList
// declare var DungeonRunner
// declare var GameConstants
// declare var GymList
// declare var MapHelper
// declare var player
// declare var PokemonHelper
// declare var pokemonList
// declare var pokemonMap
// declare var Routes
