module.exports = [
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: {
                // Environnements standards
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                Promise: 'readonly',
                fetch: 'readonly',
                jQuery: 'readonly',
                $: 'readonly',

                // Greasemonkey globals
                GM: 'readonly',
                GM_addStyle: 'readonly',
                GM_deleteValue: 'readonly',
                GM_listValues: 'readonly',
                GM_getValue: 'readonly',
                GM_setValue: 'readonly',
                GM_getResourceText: 'readonly',
                GM_getResourceURL: 'readonly',
                GM_registerMenuCommand: 'readonly',
                GM_xmlhttpRequest: 'readonly',
                unsafeWindow: 'readonly',

                // App globals
                App: 'readonly',
                BadgeEnums: 'readonly',
                Battle: 'readonly',
                BattleFrontierRunner: 'readonly',
                BreedingController: 'readonly',
                BreedingFilters: 'readonly',
                Champion: 'readonly',
                DungeonBattle: 'readonly',
                dungeonList: 'readonly',
                DungeonRunner: 'readonly',
                FarmController: 'readonly',
                GameConstants: 'readonly',
                GameHelper: 'readonly',
                Gym: 'readonly',
                GymBattle: 'readonly',
                GymList: 'readonly',
                GymRunner: 'readonly',
                ItemHandler: 'readonly',
                ItemList: 'readonly',
                KeyItemType: 'readonly',
                MapHelper: 'readonly',
                Mine: 'readonly',
                MultiplierDecreaser: 'readonly',
                NotificationConstants: 'readonly',
                Notifier: 'readonly',
                OakItemType: 'readonly',
                PartyController: 'readonly',
                player: 'readonly',
                PokemonFactory: 'readonly',
                PokemonHelper: 'readonly',
                pokemonList: 'readonly',
                pokemonMap: 'readonly',
                PokemonType: 'readonly',
                Preload: 'readonly',
                QuestHelper: 'readonly',
                Rand: 'readonly',
                RedeemableCodeController: 'readonly',
                RoamingPokemon: 'readonly',
                RoamingPokemonList: 'readonly',
                RouteHelper: 'readonly',
                Routes: 'readonly',
                SeededRand: 'readonly',
                Settings: 'readonly',
                SpecialEvents: 'readonly',
                TemporaryBattleBattle: 'readonly',
                TownList: 'readonly',
                Underground: 'readonly',
                VitaminController: 'readonly',
                Weather: 'readonly',
            },
            parserOptions: {
                ecmaFeatures: {
                    impliedStrict: true,
                },
            },
        },
        rules: {
            eqeqeq: 'warn',
            'linebreak-style': ['warn', 'unix'],
        },
        linterOptions: {
            reportUnusedDisableDirectives: true,
        },
    },
];
